### PR TITLE
Translation in French

### PR DESCRIPTION
**Pull request by alexbelgium**
https://github.com/MislavMandaric/home-assistant-vaillant-vsmart/issues/6

Naming is "fr" according to http://www.iana.org/assignments/language-subtag-registry/language-subtag-registry

### CODE REVIEW

**Comment by MislavMandaric** [comment]
Hey @alexbelgium

My PR #97 which adds reauth flow is now merged.

Can you please rebase your changes and update the translations to match the new structure?

**Comment by MislavMandaric** [comment]
Hey @alexbelgium

My PR #97 which adds reauth flow is now merged.

Can you please rebase your changes and update the translations to match the new structure?

**Comment by alexbelgium** [comment]
Thanks! I'll make sure to do that for next commits. I'll rebase tomorrow

**Comment by alexbelgium** [comment]
Creating a new pull request to follow commits semantic

**Pull request closed without merging**
